[tools]
bats = "latest"
go = "latest"
goreleaser = "latest"

[tasks.test]
run = "go test ./... -cover"

[tasks.build]
run = "go build -o dist/ ."

[tasks.integration]
run = "bats tests/"

[tasks."release:local"]
run = "goreleaser release --snapshot --clean --skip=publish"
