[tools]
bats = "latest"
go = "latest"
goreleaser = "latest"

[tasks.test]
run = "go test ./... -cover"

[tasks.build]
run = "go build -o dist/ ."

[tasks.integration]
run = "bats tests/"

[tasks."release:local"]
run = "goreleaser release --snapshot --clean --skip=publish"

[tasks."release:check"]
run = "goreleaser check"

[tasks.release]
depends = ["release:check"]
usage = '''
  arg "<tag>" help="release tag"
'''
confirm = "Are you sure you want to release helmbake {{ usage.tag }}?"
run = [
  "git tag {{ usage.tag }}",
  "git push origin {{ usage.tag }}",
]
